@"
sonar.projectKey=SIT753-Task-Manager-DevOps
sonar.projectName=SIT753 Task Manager DevOps

sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.js

sonar.exclusions=node_modules/**,coverage/**
sonar.coverage.exclusions=src/server.js

sonar.javascript.lcov.reportPaths=coverage/lcov.info
"@ | Set-Content sonar-project.properties